"""Add file_path to FileUpload


Revision ID: 1718468a1f32
Revises: c2a8fa939392
Create Date: 2024-10-16 11:04:26.888225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1718468a1f32'
down_revision = 'c2a8fa939392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_types', schema=None) as batch_op:
        batch_op.alter_column('allowed_extensions',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))  # Allow NULL


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_uploads', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    with op.batch_alter_table('file_types', schema=None) as batch_op:
        batch_op.alter_column('allowed_extensions',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
