"""Make file_path nullable

Revision ID: 5782f5469d04
Revises: 1718468a1f32
Create Date: 2024-10-16 11:09:06.284008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5782f5469d04'
down_revision = '1718468a1f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_types', schema=None) as batch_op:
        batch_op.alter_column('allowed_extensions',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_types', schema=None) as batch_op:
        batch_op.alter_column('allowed_extensions',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
